### ISSUE TITLE
[WORKAROUND] Windows binary

### ISSUE THREAD

**Issue by sergeevabc** [kddeisz/tree#2]
Dear Kevin,
Could you be so kind to generate ```.exe``` for the rest of us who are mere Windows users w/o compiler?

**Comment by JohnAZoidberg** [comment]
I think this repo is more of an exercise to try to implement it in various languages. It seems like you have that command on Windows out of the box: https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/tree
