### ISSUE TITLE
File names with space reported as separate files when using bash script

### ISSUE THREAD

**Issue by piyush-kgp** [kddeisz/tree#3]
I tried to use `tree.sh`. It ran but it reports file names with spaces as separate files
For example while I have just 1 file named "Gradient Descent.html", it displays [this](https://imgur.com/a/Glvo7wJ).

**Comment by kddeisz** [comment]
Fixed this up in here: https://github.com/kddeisz/tree/commit/1876e16118611381efde10168657dd3195ee81f4?w=1
